import type { HttpSpec } from "../engine/types";

export const HTTP_SPECS: HttpSpec[] = [
  {
    key: "stripe",
    transport: "http",
    label: "Stripe",
    baseUrl: "https://api.stripe.com",
    auth: { type: "basic", user: "{cred.secret_key}", pass: "" },
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    find: {
      method: "GET",
      path: "/v1/customers",
      query: { email: "{email}", limit: "100" },
      paginate: { type: "fullPage", pageSize: 100, nextParam: "starting_after", nextPath: "id" },
      resultsPath: "data",
      idPath: "id",
    },
    delete: { method: "DELETE", path: "/v1/customers/{res.id}", itemNoun: "customer" },
  },
  {
    key: "mailchimp",
    transport: "http",
    label: "Mailchimp",
    baseUrl: "https://{cred.server_prefix}.api.mailchimp.com/3.0",
    auth: { type: "basic", user: "anystring", pass: "{cred.api_key}" },
    find: {
      method: "GET",
      path: "/lists",
      query: { count: "100", offset: "0" },
      paginate: { type: "offset", pageSize: 100, offsetParam: "offset", totalPath: "total" },
      resultsPath: "lists",
      idPath: "id",
    },
    delete: {
      method: "POST",
      path: "/lists/{res.id}/members/{emailMd5}/actions/delete-permanent",
      successStatuses: [204],
      ignoreStatuses: [404],
      failStatuses: [401, 403],
      continueOnOther: true,
      itemNoun: "subscriber",
    },
  },
  {
    key: "hubspot",
    transport: "http",
    label: "HubSpot",
    baseUrl: "https://api.hubapi.com",
    auth: { type: "bearer" },
    find: {
      method: "POST",
      path: "/crm/v3/objects/contacts/search",
      body: () => ({
        filterGroups: [{ filters: [{ propertyName: "email", operator: "EQ", value: "{email}" }] }],
        limit: 100,
      }),
      paginate: { type: "cursorBody", param: "after", nextPath: "paging.next.after" },
      resultsPath: "results",
      idPath: "id",
    },
    delete: { method: "DELETE", path: "/crm/v3/objects/contacts/{res.id}", itemNoun: "contact" },
  },
  {
    key: "intercom",
    transport: "http",
    label: "Intercom",
    baseUrl: "https://api.intercom.io",
    auth: { type: "bearer" },
    headers: { "Intercom-Version": "2.11", "Content-Type": "application/json" },
    find: {
      method: "POST",
      path: "/contacts/search",
      body: () => ({ query: { field: "email", operator: "=", value: "{email}" }, pagination: { per_page: 100 } }),
      paginate: { type: "cursorBody", param: "starting_after", nextPath: "pages.next.starting_after" },
      resultsPath: "data",
      idPath: "id",
    },
    delete: { method: "DELETE", path: "/contacts/{res.id}", successStatuses: [200, 204], ignoreStatuses: [404], itemNoun: "contact" },
  },
  {
    key: "supabase",
    transport: "http",
    label: "Supabase",
    baseUrl: "{cred.project_url}",
    auth: { type: "bearer" },
    headers: { apikey: "{cred.service_role_key}" },
    find: {
      method: "GET",
      path: "/auth/v1/admin/users",
      query: { email: "{email}" },
      resultsPath: "users",
      idPath: "id",
    },
    delete: { method: "DELETE", path: "/auth/v1/admin/users/{res.id}", itemNoun: "user" },
  },
];
