/**
 * Static list of integrations supported by NukeAPI.
 * Values are the exact slugs the NukeAPI REST API expects.
 */
export const INTEGRATIONS: string[] = [
  'stripe', 'mailchimp', 'hubspot', 'intercom', 'supabase', 'postgresql',
  'salesforce', 'segment', 'klaviyo', 'sendgrid', 'auth0', 'clerk',
  'posthog', 'zendesk', 'mixpanel', 'mysql', 'planetscale', 'neon',
  'mongodb', 'firestore', 'convertkit', 'activecampaign', 'resend', 'drip',
  'amplitude', 'fullstory', 'heap', 'june', 'paddle', 'chargebee',
  'recurly', 'braintree', 'pipedrive', 'freshdesk', 'crisp', 'firebaseauth',
  'okta', 'stytch', 'turso', 'redis', 'elasticsearch', 'cassandra', 'workos',
  'passage', 'cognito', 'keycloak', 'brevo', 'omnisend', 'beehiiv',
  'substack', 'loops', 'customerio', 'linear', 'helpscout', 'gorgias',
  'groove', 'smartlook', 'logrocket', 'datadog', 'pendo', 'lemonsqueezy',
  'gumroad', 'zuora', 'awss3', 'cloudflarer2', 'googlecloudstorage',
  'vercelblob', 'twilio', 'vonage', 'plivo', 'notion', 'airtable',
  'webflow', 'memberstack', 'outseta', 'braze', 'iterable', 'vero',
];

const LABEL_OVERRIDES: Record<string, string> = {
  postgresql: 'PostgreSQL',
  awss3: 'AWS S3',
  cloudflarer2: 'Cloudflare R2',
  googlecloudstorage: 'Google Cloud Storage',
  vercelblob: 'Vercel Blob',
  firebaseauth: 'Firebase Auth',
  sendgrid: 'SendGrid',
  posthog: 'PostHog',
  zendesk: 'Zendesk',
  mixpanel: 'Mixpanel',
  mysql: 'MySQL',
  planetscale: 'PlanetScale',
  mongodb: 'MongoDB',
  firestore: 'Firestore',
  convertkit: 'ConvertKit',
  activecampaign: 'ActiveCampaign',
  resend: 'Resend',
  amplitude: 'Amplitude',
  fullstory: 'FullStory',
  chargebee: 'Chargebee',
  recurly: 'Recurly',
  braintree: 'Braintree',
  pipedrive: 'Pipedrive',
  freshdesk: 'Freshdesk',
  crisp: 'Crisp',
  okta: 'Okta',
  stytch: 'Stytch',
  turso: 'Turso',
  redis: 'Redis',
  elasticsearch: 'Elasticsearch',
  cassandra: 'Cassandra',
  workos: 'WorkOS',
  passage: 'Passage',
  cognito: 'Cognito',
  keycloak: 'Keycloak',
  brevo: 'Brevo',
  omnisend: 'Omnisend',
  beehiiv: 'Beehiiv',
  substack: 'Substack',
  loops: 'Loops',
  customerio: 'Customer.io',
  linear: 'Linear',
  helpscout: 'HelpScout',
  gorgias: 'Gorgias',
  groove: 'Groove',
  smartlook: 'SmartLook',
  logrocket: 'LogRocket',
  datadog: 'Datadog',
  pendo: 'Pendo',
  lemonsqueezy: 'LemonSqueezy',
  gumroad: 'Gumroad',
  zuora: 'Zuora',
  twilio: 'Twilio',
  vonage: 'Vonage',
  plivo: 'Plivo',
  notion: 'Notion',
  airtable: 'Airtable',
  webflow: 'Webflow',
  memberstack: 'MemberStack',
  outseta: 'Outseta',
  braze: 'Braze',
  iterable: 'Iterable',
  vero: 'Vero',
  klaviyo: 'Klaviyo',
  segment: 'Segment',
  salesforce: 'Salesforce',
  hubspot: 'HubSpot',
  intercom: 'Intercom',
  supabase: 'Supabase',
  mailchimp: 'Mailchimp',
  stripe: 'Stripe',
  auth0: 'Auth0',
  clerk: 'Clerk',
  drip: 'Drip',
  heap: 'Heap',
  june: 'June',
  paddle: 'Paddle',
};

export function prettyLabel(slug: string): string {
  return LABEL_OVERRIDES[slug] ?? slug.charAt(0).toUpperCase() + slug.slice(1);
}
